### PR TITLE
React 17 and classname

### PR DESCRIPTION
**Pull request by merlijn**
I wanted to use this module in my project but needed to change a few things to make it work.

- Make it work with react 17
- Allow className to be passed in the props

What do you think?

### CODE REVIEW

**Comment by sanishkr** [comment]
@merlijn I understand the React 17 use case. If it is breaking for v17, please send a separate PR and I can help.
But I don't understand the use-case of passing `className` as a prop simply to return it. You can pass any other prop to your child component you want already like alt, style, etc.

Here is an example:
```
<ProgressiveImage src="large-image.jpg" placeholder="tiny-image.jpg" >
  {(src) => {
    return (
      <div>
        <img className="progressive-image" src={src} />
      </div>
    );
  }}
</ProgressiveImage>
```

Let me know any specific use-case which I missed here or better make a sandbox.

PS: The order of existing props in returning function has to remain the same. Any newly added prop has to be pushed to the end to make sure nothing breaks for devs using prev versions.

**Comment by merlijn** [comment]
Ah, I see. I did not really take time to understand the code, probably my misunderstanding. So in your example will the placeholder image also use the className? 

In my code I have now something like:

```
   <ProgressiveImage src="someImage.jpeg" placeholder="placeholder.jpeg" className="someClass"> 
   { (src) => { return ( <img className="progressive-image" src={src} /> ); } }
  </ProgressiveImage>
```

Thanks for making this module btw. It has already been helpful :)

I can make a separate PR for the react 17 part 👍

**Comment by merlijn** [comment]
@sanishkr 

Never mind. I tried your suggestion and it works like a charm :). Sorry for the confusion.

**Comment by sanishkr** [comment]
It's alright. Glad to help.
And thanks for appreciating.
😊

**Pull request closed without merging**
